### PR TITLE
Added gspreadsheets module

### PR DESCRIPTION
**Pull request by andrewzolotukhin**
I use Google Spreadsheets to store some statistics and aggregate it there, in my dashboard I'd like to see some data from this spreadsheet in form:
Name1   Value1
Name2   Value2
Name3   Value3

Added sample config to complex_config.yml.

### CODE REVIEW

**Comment by senorprogrammer** [comment]
Sweet. I'll try to test this out this weekend. Thanks!

**Comment by andrewzolotukhin** [comment]
Ok, ask me if you have any questions.

**Comment by senorprogrammer** [comment]
Great PR - thank you!

**Comment by andrewzolotukhin** [comment]
No problem, going to add a new one soon.

**Pull request merged**
