### PR TITLE
Some Windows Support 

### LINKED ISSUE #103: Windows Support
Great project! I'm a Windows guy, so naturally I tried it on Windows in PowerShell. Works for me with `go build -v -o wtf.exe` or `go install -v` since I didn't have `make` installed.

There are some areas that do need fixing, but I wanted to start a top level issue with some of what I see out of the box with a vanilla config:

- [] Bad Character Encoding in the box headers.
- [] Linux-specific tools used.
- [] `Makefile` only works on Linux.

image

You can see some of the issues in the screenshot. If you can point me to where that code exists, I might be able to help make it work as intended on Windows.

### PR DESCRIPTION
**Pull request by mxplusb**
Starts to fix #103. Not sure what full support would look like, but this is a start. In retrospect, I likely should've branched instead of doing this on master.

### CODE REVIEW

**Comment by senorprogrammer** [comment]
I have no way to test this out. It would be great to have this code-reviewed and corroborated by a few other people.

**Comment by mxplusb** [comment]
Sure. There's no rush.

**Comment by senorprogrammer** [comment]
One question I'm not clear on from the code: how does it know which platform to load? For example, with `dns_darwin.go` and `dns_windows.go`, how does it know which one to use?

**Comment by senorprogrammer** [comment]
Also, could you rebase against master for me? Once I understand this a bit better and the rebase is done, I'll merge it in. Thanks!

**Comment by mxplusb** [comment]
@senorprogrammer when you do `go build`,  the compiler will build the binary based off the target OS. So if your `GOOS` is darwin, which is the default for macos, it will build anything with the `*_darwin.go* flags. You can find more information on [golang build tags here](https://golang.org/pkg/go/build/#hdr-Build_Constraints) - I just use the `*_windows.go` build tag since they are nearly identical and it's easier for us humans to understand. :)

**Comment by senorprogrammer** [comment]
Awesome. Thank you for the explanation. If you're able to rebase this against master, I'll merge it in.

**Comment by senorprogrammer** [comment]
Just touching base. No hurry, when you're able to rebase this against master, I'll merge it right in.

**Comment by mxplusb** [comment]
Should be good now.

**Comment by mxplusb** [comment]
Also, feel free to ping me for Windows stuff down the road since that's my domain. It's a nifty tool and would love to see better support for it.

**Comment by mxplusb** [comment]
Travis is failing because you have `go get ./... && go get github.com/go-test/deep && go test -v github.com/senorprogrammer/wtf/wtf_tests` as one command and I don't know which part of it is failing, so I can't fix my builds until you're able to fix Travis.

**Comment by senorprogrammer** [comment]
The following errors:
```
18.51s$ go get ./... && go get github.com/go-test/deep && go test -v github.com/senorprogrammer/wtf/wtf_tests
# github.com/senorprogrammer/wtf/security
security/security_data.go:24:13: undefined: DnsServers
security/security_data.go:27:23: undefined: LoggedInUsers
# github.com/senorprogrammer/wtf/system
system/widget.go:17:14: undefined: SystemInfo
```
TravisCI runs on Linux and the changes you've made are now Mac & Windows-only. 

Take a look at the way `power/battery.go` and `power/batter_linux.go` are defined at the top of the file. This might be fixed by adding `// +build !windows` and `// +build windows` to the respected files.

In the meantime I'll look into getting TravisCI to present useful error messages somehow.

**Comment by mxplusb** [comment]
I think it would be good to cross-compile, but I'm not sure what that would look like on Travis.

**Comment by senorprogrammer** [comment]
Got it working. Thanks for making this PR!

**Pull request merged**
