### PR TITLE
Added PrettyWeather mod

### LINKED ISSUE #112: Feature: Pretty Weather Module
Yet another weather module with ascii art would be nice. BTW WTF is amazing!

### PR DESCRIPTION
**Pull request by FarhadF**
Closes #112.

Pretty Weather Module:
Yet another weather module for WTF, using geeks favorite wttr.in weather system. 

Config sample:
```
    prettyweather:
      enabled: true
      city: "tehran" #can be omited, will grab current location from ip address.
      unit: "c" #can be omited, will use metric if you are out of US and imperial for US. can be either "c" or "u"
      position:
        top: 0
        left: 2
        height: 1
        width: 2
      refreshInterval: 300 
```
Screenshot:
image

### CODE REVIEW

**Comment by senorprogrammer** [comment]
Running this branch in iTerm2, I get the following output. Looks like it's not reading the ANSI codes. Any thoughts?

screen shot 2018-06-01 at 6 13 03 pm

**Comment by FarhadF** [comment]
Im, running linux so I cant investigate firsthand, but could you please try https://superuser.com/a/448892/639276

**Comment by senorprogrammer** [comment]
Getting closer. Updating the `tcell` and/or `tview` libraries got it to this.
screen shot 2018-06-01 at 11 35 17 pm

**Comment by FarhadF** [comment]
Could you please increase the width and height in the config, set them both to 3 for testing purposes.

**Comment by senorprogrammer** [comment]
Increasing the width has it displaying properly. I'm seeing some strange artifacting from it in other widgets which I suspect might be an issue with the ANSI codes that Wttr is returning (see right-hand side of border in this screenshot for an example).

I'm going to add a category of module called "Experimental" and mark this one as that so it can get into master for others to play with. Someone else might have some insight into these cosmetic issues.

screen shot 2018-06-02 at 5 06 28 am

**Comment by senorprogrammer** [comment]
Ignore the CodeClimate stuff - some issues it will find are currently unresolvable with the existing widget design.

**Comment by FarhadF** [comment]
I resolved the conflict on web interface yet I messed up the formatting, let me fmt the wtf.go

**Comment by FarhadF** [comment]
Should be clean now.

**Comment by senorprogrammer** [comment]
All good, I fixed the conflicts on my local branch. It's in master now. Take a look, let me know if it's working properly for you.

**Comment by FarhadF** [comment]
I just tested the master, looks good, but we sure need more feedback, colors are tricky.

**Pull request closed without merging**
