### PR TITLE
Advanced Jira Search.

### PR DESCRIPTION
**Pull request by sherodtaylor**
added support for custom JQL

### CODE REVIEW

**Comment by senorprogrammer** [comment]
This looks great. Could you add a comment with an example of how custom JQL would be used/added to config in this case so I can understand the outcome?

**Comment by sherodtaylor** [comment]
So what this is doing is  creating a base query 
`assignee = "staylor" AND project = "Scrum"` 

Then if the param jql is inserted it would also add that like 
yaml
```
jql:  "priority in (Blocker, Critical)"
assignee: "staylor"
project: "Scrum"
```

would translate to
`assignee = "staylor" AND project = "Scrum" AND priority in (Blocker, Critical)`

Here's a good intro to JQL https://confluence.atlassian.com/jiracore/blog/2015/07/search-jira-like-a-boss-with-jql

**Comment by senorprogrammer** [comment]
Thanks for the details. I'll give this a try against our Jira install.

**Comment by senorprogrammer** [comment]
Thanks! Merged.

**Pull request merged**
