### PR TITLE
WIP - Add hackernews module - wait for rebase

### PR DESCRIPTION
**Pull request by anandsudhir**
Add hackernews module.

I will rebase this PR after #278 is merged

### CODE REVIEW

**Comment by senorprogrammer** [comment]
Is this WIP because you were waiting for the rebase, or because there's still more you want to add to it?

**Comment by anandsudhir** [comment]
It's because I'm waiting to rebase.

**Comment by anandsudhir** [comment]
Awesome, thanks :)

**Comment by senorprogrammer** [comment]
I love this PR. Another browser tab I don't have to keep open :)

**Pull request merged**
