### PR TITLE
Introduce wtf installer

### PR DESCRIPTION
**Pull request by deltaxflux**
Hey,

Since #130, I decided to create a quick installer. The installer uses the dialog utils but I will create a option that you don't have to use these. You can try it, working fine on arch, debian and ubuntu. I don't have an option to try it on mac OS but you can do it.

Quick fix of the Makefile would be to add
```
ln -s $GOPATH/bin/wtf /bin/wtf
```

But the installer is working fine of course.

Regards,

deltax

### CODE REVIEW

**Comment by senorprogrammer** [comment]
How come this was closed?

**Comment by deltaxflux** [comment]
Because of a lack of response.

**Comment by senorprogrammer** [comment]
You only opened that PR two days ago. `WTF` ain't my job, it's my side-project. I have a lot of other things in life that need attention as well. Be patient, stay tuned. I don't ignore PRs and hope they go away, I close the ones I don't want. If it's open, it'll be addressed at some point.

**Comment by deltaxflux** [comment]
Well, I thought that the installer isn't necessary because you ignored it. Don't get me wrong, keep it up.

**Comment by senorprogrammer** [comment]
Ha! Given how much trouble people have been having getting it installed, I think an installer is probably critical 😄 

Right up there with @jeangovil's PR #62 that only loads modules the config specifies should be loaded. Haven't had a chance to get to that one either.

**Comment by senorprogrammer** [comment]
Thank you for taking the time to build this.

**Comment by senorprogrammer** [comment]
Looks to me like this is Linux-only. There is a Homebrew package for `dialog` but I'm not a fan of people having to first install software to then install this (and it's entirely possible they may not have Homebrew).

**Comment by senorprogrammer** [comment]
Also note that this deleted `$GOPATH/src/github.com/senorprogrammer/wtf` and everything in it. I think this still needs some work.

**Comment by deltaxflux** [comment]
Yeah absolutely, don't thought about the dialog is not present on mac os. I will fix this in these days.

**Comment by deltaxflux** [comment]
Well I now added OSX support.

**Comment by senorprogrammer** [comment]
Still throwing local errors in MacOS. Still trying to use `dialogrc`?

```
❯ make install
bash installer.sh
WTF gui installer

[  - ]	Initalize all filescp: misc/.dialogrc: No such file or directory
[fail]
[  | ]	Clean old files and remove binariescan't load package: package github.com/senorprogrammer/wtf: cannot find package "github.com/senorprogrammer/wtf" in any of:
	/usr/local/Cellar/go/1.10.2/libexec/src/github.com/senorprogrammer/wtf (from $GOROOT)
	/Users/chris/go/src/github.com/senorprogrammer/wtf (from $GOPATH)
[fail]
[  | ]	Install latest and required dependencies# cd .; git clone https://github.com/senorprogrammer/wtf /Users/chris/go/src/github.com/senorprogrammer/wtf
Cloning into '/Users/chris/go/src/github.com/senorprogrammer/wtf'...
fatal: Unable to read current working directory: No such file or directory
package github.com/senorprogrammer/wtf: exit status 128
[fail]
[  | ]	Install wtflib/installer/WtfInstaller.sh: line 46: shell: command not found
lib/installer/WtfInstaller.sh: line 46: shell: command not found
can't load package: package github.com/senorprogrammer/wtf: cannot find package "github.com/senorprogrammer/wtf" in any of:
	/usr/local/Cellar/go/1.10.2/libexec/src/github.com/senorprogrammer/wtf (from $GOROOT)
	/Users/chris/go/src/github.com/senorprogrammer/wtf (from $GOPATH)
[fail]
[  | ]	Build wtfcan't load package: package github.com/senorprogrammer/wtf: cannot find package "github.com/senorprogrammer/wtf" in any of:
	/usr/local/Cellar/go/1.10.2/libexec/src/github.com/senorprogrammer/wtf (from $GOROOT)
	/Users/chris/go/src/github.com/senorprogrammer/wtf (from $GOPATH)
```

**Comment by deltaxflux** [comment]
Interesting. No I don't use dialog anymore I made a bash spinner which should work. Let's see if I could figure out whats going wrfong. Working fine on linux both :)

**Comment by senorprogrammer** [comment]
It appears to be related to this line `readonly DIALOG="$HOME/.dialogrc"` though I don't see where `DIALOG` is being used.

**Comment by senorprogrammer** [comment]
I'm wrong, it's this line: `if [ ! -f "$HOME/.dialogrc" ];then cp misc/.dialogrc $HOME;fi`

**Comment by deltaxflux** [comment]
Can you try it ?

**Comment by senorprogrammer** [comment]
Yep, I'll try to do that this evening.

**Comment by deltaxflux** [comment]
Since I not in deep with this project, this is the latest commit. You can try to run this again. It works on linux but as I mentioned I have no opportunity to run this on any MAC OSX machine.

**Comment by senorprogrammer** [comment]
Thanks for your work @deltaxflux. I'll see if I can pick it up from here on MacOS.

**Comment by deltaxflux** [comment]
.

**Comment by senorprogrammer** [comment]
Hoping to pick this up this coming week (I'm on vacation, should be able to devote some concerted effort to WTF).

**Comment by senorprogrammer** [comment]
Back from vacation and will be looking at merging this.

**Pull request closed without merging**
