### PR TITLE
Vendor dependencies using golang/dep

### PR DESCRIPTION
**Pull request by rubiojr**
Output from `dep status`:

```
PROJECT                               CONSTRAINT     VERSION        REVISION  LATEST   PKGS USED
cloud.google.com/go                   v0.23.0        v0.23.0        0fd7230   v0.23.0  1
github.com/briandowns/openweathermap  ^0.11.0        0.11           1b87579   0.11     1
github.com/gdamore/encoding           branch master  branch master  b23993c   b23993c  1
github.com/gdamore/tcell              ^1.0.0         v1.0.0         061d51a   v1.0.0   2
github.com/go-test/deep               ^1.0.1         v1.0.1         6592d9c   v1.0.1   1
github.com/golang/protobuf            v1.1.0         v1.1.0         b4deda0   v1.1.0   1
github.com/google/go-github           ^15.0.0        v15.0.0        e48060a   v15.0.0  1
github.com/google/go-querystring      branch master  branch master  53e6ce1   53e6ce1  1
github.com/jessevdk/go-flags          ^1.4.0         v1.4.0         c6ca198   v1.4.0   1
github.com/lucasb-eyer/go-colorful    v1.0           v1.0           345fbb3   v1.0     1
github.com/mattn/go-runewidth         v0.0.2         v0.0.2         9e777a8   v0.0.2   1
github.com/olebedev/config            branch master  branch master  9a10d05   9a10d05  1
github.com/radovskyb/watcher          ^1.0.2         v1.0.2         6145e14   v1.0.2   1
github.com/rivo/tview                 branch master  branch master  71ecf1f   71ecf1f  1
github.com/yfronto/newrelic           branch master  branch master  f7fa0c6   f7fa0c6  1
golang.org/x/net                      branch master  branch master  1e49130   1e49130  2
golang.org/x/oauth2                   branch master  branch master  1e0a3fa   1e0a3fa  5
golang.org/x/text                     v0.3.0         v0.3.0         f21a4df   v0.3.0   5
google.golang.org/api                 branch master  branch master  00e3bb8   00e3bb8  4
google.golang.org/appengine           v1.0.0         v1.0.0         150dc57   v1.0.0   10
gopkg.in/yaml.v2                      ^2.2.1         v2.2.1         5420a8b   v2.2.1   1
```

See https://golang.github.io/dep/docs/daily-dep.html

### CODE REVIEW

**Comment by rubiojr** [comment]
Should be ready to go!

**Comment by senorprogrammer** [comment]
Thanks @rubiojr! Could you bring this up-to-date with master for me and then I'll merge it in?

**Comment by rubiojr** [comment]
Sure thing.

Would you like me to add a basic `.travis.yml` to make sure it builds while we're at it?

**Comment by rubiojr** [comment]
> Could you bring this up-to-date with master for me and then I'll merge it in?

Done.

**Comment by rubiojr** [comment]
> Done.

Wait, missed there are some new deps probably.

**Comment by rubiojr** [comment]
> Wait, missed there are some new deps probably.

Double checked. Not required.

**Comment by senorprogrammer** [comment]
Thanks!

**Comment by senorprogrammer** [comment]
@rubiojr Thank you very much for doing this. As a final step, would you mind adding some docs to the README about how to update the dependencies using `dep`? We're already seeing an issue (not caused by your PR - https://github.com/senorprogrammer/wtf/issues/173) in which the vendored dep is buggy and needs to be updated.

**Comment by rubiojr** [comment]
@senorprogrammer definitely. I'll open a PR tomorrow.

**Comment by senorprogrammer** [comment]
Thank you sir.

**Pull request merged**
