### PR TITLE
Add Travis CI config

### PR DESCRIPTION
**Pull request by rubiojr**
Currently it only tests that wtf builds.

### CODE REVIEW

**Comment by rubiojr** [comment]
@senorprogrammer you'll need to go through something like https://docs.travis-ci.com/user/getting-started to add this repo to Travis.

**Comment by BillKeenan** [comment]
adding this to the end will run the tests

```script: go get ./... && go get github.com/go-test/deep && go test -v github.com/senorprogrammer/wtf/wtf_tests```

**Comment by BillKeenan** [comment]
here it is working FYI
https://travis-ci.org/BillKeenan/wtf

**Comment by senorprogrammer** [comment]
Done. Thanks @rubiojr and @BillKeenan

**Pull request merged**
